### ISSUE TITLE
fyi: Electron 4.0.0

### ISSUE THREAD

**Issue by JayBrown** [nickjwhite/diogenes#11]
I'm not sure if the final Diogenes NG software will be an Electron app, but fyi: Electron 4.0.0 has just been released:

https://github.com/electron/electron/releases
https://electronjs.org/blog/electron-4-0

**Comment by nickjwhite** [comment]
Thanks alot for the tip @JayBrown, that is indeed useful, we will be releasing this as an Electron app soon, and hadn't thought to check for new versions. Happily nothing much had to change to be fully compatible, I just updated with commit 9cf8937.
