### ISSUE TITLE
Diogenes and Peter Heslin's Diogenes?

### ISSUE THREAD

**Issue by glengemann** [nickjwhite/diogenes#2]
What is the different between this Diogenes and Peter Heslin's [Diogenes](https://community.dur.ac.uk/p.j.heslin/Software/Diogenes/index.php)?.

**Comment by nickjwhite** [comment]
Hi, thanks for the question. This is the code for the new version of Peter Heslin's Diogenes, which includes input from Peter. It is based on nwjs, rather than xulrunner, as the latter is deprecated. We haven't had much time to finish it lately, but it's nearly ready for release now.
