### ISSUE TITLE
[INFO] make on OS X and macOS: shasum instead of sha256sum

### ISSUE THREAD

**Issue by JayBrown** [nickjwhite/diogenes#4]
You can `make` the Diogenes server on OS X and macOS, but you first need to replace all instances of `sha256sum -c` with `shasum -c -a 256` in `./makefile` and `./mk.commondata`

Maybe you could add an OS check to the makefile and include the optional macOS command.

Personal note: **thank you *so much*** for updating Diogenes. The original xulrunner app will probably not work anymore on future OS versions, and I never got the original perl server working.

PS: I'll test this further, over the next days probably, and get back, if there are any problems. First observation: `make -f mk.perseusdata` definitely failed with errors, but I'll first test it with the precompiled downloads.

**Comment by JayBrown** [comment]
Update: seems to work fine with TLG/PHI prebuilt morphology data.

**Comment by nickjwhite** [comment]
@JayBrown, many thanks for letting me know about this, sorry I missed it until now.

If you have time, please send me a pull request with this and I'll happily accept it. If not I'll certainly make sure I sort it out myself soon enough.

**Comment by nickjwhite** [comment]
Oh, and in response to your personal note, you're most welcome, and Peter Heslin has been helping me behind the scenes too! I'm back to spending time on this again now, so we should be able to make a proper release in not too long. As you say, the xulrunner approach is very much on borrowed time at this point.

**Comment by nickjwhite** [comment]
This is finally done now, thanks to 47af25. Thanks again for reporting it.
