### ISSUE TITLE
Font/text display issues

### ISSUE THREAD

**Issue by JayBrown** [nickjwhite/diogenes#6]
There are font/text display issues; example using κέρας

Original application:

![screengrab1](https://i.imgur.com/ebbGFYw.jpg)

Server version:

![screengrab2](https://i.imgur.com/PGUKvqR.jpg)

The latter uses Alphabetum Unicode as the font, but the display bug also occurs with the default font, which would be Times New Roman. (?)

Output setting is UTF-8.

**Comment by JayBrown** [comment]
Server version using default font:

![screengrab3](https://i.imgur.com/kjUUzKy.jpg)

**Comment by Doc73** [comment]
Found a workaround. You can see it a #7

**Comment by nickjwhite** [comment]
Duplicate of #7
